# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# permissions for end users to view ipprefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipprefix-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ipam
    app.kubernetes.io/part-of: ipam
    app.kubernetes.io/managed-by: kustomize
  name: ipprefix-viewer-role
rules:
- apiGroups:
  - ipam.nephio.org
  resources:
  - ipprefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.nephio.org
  resources:
  - ipprefixes/status
  verbs:
  - get
