# permissions for end users to edit ipaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipaddress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ipam
    app.kubernetes.io/part-of: ipam
    app.kubernetes.io/managed-by: kustomize
  name: ipaddress-editor-role
rules:
- apiGroups:
  - ipam.nephio.org
  resources:
  - ipaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.nephio.org
  resources:
  - ipaddresses/status
  verbs:
  - get
