# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# permissions for end users to edit ipallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ipallocation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ipam
    app.kubernetes.io/part-of: ipam
    app.kubernetes.io/managed-by: kustomize
  name: ipallocation-editor-role
rules:
- apiGroups:
  - ipam.nephio.org
  resources:
  - ipallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.nephio.org
  resources:
  - ipallocations/status
  verbs:
  - get
