# permissions for end users to view networkinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networkinstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ipam
    app.kubernetes.io/part-of: ipam
    app.kubernetes.io/managed-by: kustomize
  name: networkinstance-viewer-role
rules:
- apiGroups:
  - nephio.org.nephio.org
  resources:
  - networkinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nephio.org.nephio.org
  resources:
  - networkinstances/status
  verbs:
  - get
